name: maxit_cli
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

executables:
  maxit: main
environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  cli_completion: ^0.5.1
  mason_logger: ^0.3.2
  path: ^1.9.1
  path_provider: ^2.1.5
  pub_updater: ^0.5.0
  yaml: ^3.1.3
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
